version: '3.8'

services:
  php-apache:
    build: .
    container_name: parag_portfolio
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=hadiyaparag12@gmail.com
      - MAIL_PASSWORD=root
